import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./components/BootstrapClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} data-bs-theme="dark">
        <nav className="navbar bg-body-tertiary">
          <div className="container-fluid">
            <a className="navbar-brand" href="/">
              EmotionGram <i className="bi bi-instagram"></i>
            </a>
          </div>
        </nav>
        <div className="container">
          {children}
        </div>
        <footer className="footer mt-auto py-3 bg-body-tertiary">
          <div className="container">
            <p className="text-center">
              Made with ❤️ by <a href="">{"@bagusa4"}</a>
            </p>    
          </div>          
        </footer>
        <BootstrapClient />
      </body>
    </html>
  );
}
